### ISSUE TITLE
Pressure Sensor Data

### ISSUE THREAD

**Issue by AlyciaStorch** [AguaClara/ram_pump#43]
Below are graphs from pressure sensor data taken using two different springs. The end of the pump was submerged for both. The big spikes are clearly where the plate closes all the way. We suspect the smaller concave down curves before the spikes are when the plate is closing but **we can't tell when the plate is opening**. It looks like there might be a point of inflection after the spike at a similar pressure as closing, could this be it? What does it mean that it is a point of inflection (if it is)?  Additionally with the closing curves, we originally took data when the end of the pump was not submerged and got very similar data. In this case, the peak of the closing curve corresponds to a force much greater than the calculated force needed to close the spring. The local min of the closing curve right before the spike is close to the calculated value. How can the force exceed the force needed to close the spring before the plate actually closes? Should we be factoring in the pressure below the plate as something other than atmospheric when the end of the pump is NOT submerged? Why did these values not change much when the pump is submerged?
@monroews @mailemccann any ideas?

![88 graph](https://user-images.githubusercontent.com/35945399/48747967-3753c180-ec43-11e8-819d-b9508b7ca218.png)
![2 49 graph](https://user-images.githubusercontent.com/35945399/48748010-61a57f00-ec43-11e8-916b-d27a0445df89.png)

**Comment by monroews** [comment]
A couple of ideas and recommendations.

Under what condition did you zero the sensor? If you zeroed it under zero flow with the drive pipe full of water (my recommendation) then I'd expect the pressure to never go negative. So that is my first confusion.

Change the x axis to a meaningful unit. I'd suggest milliseconds! This is a critical part of creating plots that can be interpreted. And zero the start time for your graph. Time since midnight doesn't have any relevance for your data.

Measure the time between the high spikes. That time might be the time for a pressure wave to travel from the valve to the head tank and back to the valve. You can use the speed of sound in water to check this out.

Add a pressure sensor on the high pressure pumped water side. That will help you identify when water is being pumped. By plotting both sensors on the same graph it should become clear what is happening.

Now you can calculate cycle times and compare expectation with measurements!

I am not yet able to interpret the pressure trace. I wonder if there is significant air in the pressure sensor connection tubing and if that is moving around and confusing the reading. You should be able to see (with your eyes) if the air/water interface in the pressure sensor connector tubing is fluctuating during the test.
