### ISSUE TITLE
Set up Ram Pump Pulley System

### ISSUE THREAD

**Issue by cheertsang** [AguaClara/ram_pump#46]
- [x] Add sliding platform for balance
- [x] Figure out how to get pump to start pumping water to head tank
- [ ] Test out weights

**Comment by cheertsang** [comment]
Monroe's Tips
Can your balance read a negative value if you zero it with a mass on the balance? If so, then I suggest the following

1. Close a manual valve that you install BELOW the ram pump
2. Fill the drive pipe with water. Make sure it is completely full and there is no air trapped in the ram pump. You can tap the ram pump to release any captured air.
3. Place a mass on the balance 
4. Zero the balance
5. Connect the mass to the nylon strand.
6. Lower the balance slowly until the mass reading stays constant as you lower the balance because you have lifted the valve. (record this mass as it is the force required to lift the valve at the end of the valve closed part of the cycle

How will you measure the force that results in the valve closing again? I propose the following

1. Hold the valve open with the nylon strand by lowering the balance to the location that opens the valve the required amount. (I"m not exactly sure how to do this, but I think you can figure this out.) Make sure there is a positive stop on how far the valve can open so you can detect that stop with the balance. Record the zero flow balance reading.
2. Now slowly increase the flow of water through the ram pump by slowly opening the valve that is located below the ram pump. Measure the flow rate somehow at several different valve positions.Record the balance reading. The balance reading (Minus the previous reading under zero flow) will give you the force of water (drag) on the valve.
3. Plot this data.
4. This will give you the force on the valve as a function of flow rate and thus this will enable you to pick a spring force that matches the flow rate at which you want the valve to close.
5. Use the two forces and the change in spring length between these two positions to design a spring (length and k valve) that delivers both forces (if possible).

**Comment by cheertsang** [comment]
@monroews we are a little confused on the point at which we measure the mass reading as we lower balance because there isn't really a clear range where the mass reading is constant. Our understanding is that we are using the balance to measure the tension force of the string, so initially the string is exerting no tension force on the bottle. As we lower the balance, the tension force is increasing. At some point during this, the valve opens, which would presumably relieve the tension force briefly?

**Comment by monroews** [comment]
Presumably as soon as the valve stem lifts off of the valve seat the balance is finally reading the weight of the  valve stem. Then if you lower the balance slightly you should get the SAME reading because the valve seat is still suspended by the balance. But if you lower the balance too far, then the valve seat will hit the stop that prevents it from going any higher. At that point the reading on the balance will drop.

**Comment by monroews** [comment]
Opening the valve doesn't relieve the force! once the valve begins to open you should see the maximum force.

**Comment by ChingPangggg** [comment]
We connected the pulley system to the balance using a bottle filled with water as our mass. However, we find it difficult to find the force required to lift the valve still. When we were lowering the the balance, we found it difficult to precisely adjust the height even with the use of a handle, because moving the height very slightly changes the reading by a lot. We also cannot find the period where the reading remains constant. Would you please advise us on this? @monroews

**Comment by ChingPangggg** [comment]
We found the approximate point to be 153.5 g, 136 g, 128 g, 142 g, and 170 g respectively in different trials. In addition, last semester, the team proposed another method to measure the force 

> The other end of the string was tied to a water bottle that was suspended in the air and acted as a counter weight. The bottle had enough water in it to keep the plate open while the pump was running. Then, with the pump still running, the team emptied the bottle little by little until the plate was no longer held open by the bottle. The team then used a pipette to slowly add water back into the bottle until the plate was held open again.

Do you think that this method would be more accurate?

**Comment by monroews** [comment]
Now that you have the balance at the correct height so that the balance is supporting the weight of the valve stem, now you can vary the flow rate and measure the change in force on the valve stem. Now that the balance is at the correct height it should be possible to get all of the measurements quickly.

**Comment by monroews** [comment]
You can check the weight by measuring the mass of the valve stem in the air and then correcting that for buoyancy. You can find the density of stainless steel online.
