### ISSUE TITLE
Theoretical Volume of Water Pumped

### ISSUE THREAD

**Issue by cheertsang** [AguaClara/ram_pump#67]
@monroews We are writing code to calculate the theoretical volume of water pumped during each cycle so that we can compare this to the experimental values. This is the equation that we're using, and we're using the terminal velocity we found by experimentation:

<img width="634" alt="Screen Shot 2019-04-11 at 5 22 41 PM" src="https://user-images.githubusercontent.com/35718077/55994026-9eb7ef80-5c7e-11e9-8364-21fe7c010415.png">

Our question is, **what is the delta t that we're using? Is it the time difference between opening and closing the valve?**
![pressure_trace_initialpressure0325_onecycle](https://user-images.githubusercontent.com/35718077/55994059-b1cabf80-5c7e-11e9-826f-c1b72774cb3e.jpg)

**Or is it the time difference when water is actually being pumped into the air chamber?**
(between roughly 0.02 and 0.07 s) - this graph below is a close-up of the graph above, when the pressure in the waste valve exceeds the pressure in the air chamber
![water_pumped_closeup](https://user-images.githubusercontent.com/35718077/55994467-c491c400-5c7f-11e9-8360-7d7bf1ff56e5.jpg)

Thank you!

**Comment by monroews** [comment]
The theoretical maximum value that you can pump is based on the time required to decelerate the water that is traveling at the terminal velocity given that you are applying a pressure to the bottom of the drive pipe. 

Use the difference in pressure between the static pressure in the drive pipe and the pressure in the high pressure system to find the pressure that is decelerating the flow in the drive pipe. In an ideal system it would decelerate at a constant rate because the pressure would be constant.  I believe you derived the equation to calculate this delta t in our previous meeting.

**Comment by monroews** [comment]
The empirical measurement of the delta t is close to 0.04 seconds as shown in the second graph.

**Comment by cheertsang** [comment]
We derived this expression for delta t:
<img width="234" alt="Screen Shot 2019-04-12 at 4 05 07 PM" src="https://user-images.githubusercontent.com/35718077/56066536-1270ff80-5d46-11e9-8993-1721185c3caf.png">
<img width="112" alt="Screen Shot 2019-04-12 at 4 04 59 PM" src="https://user-images.githubusercontent.com/35718077/56066560-2157b200-5d46-11e9-85a7-f5d74bff4ae3.png">
<img width="153" alt="Screen Shot 2019-04-12 at 4 05 12 PM" src="https://user-images.githubusercontent.com/35718077/56066277-4ac40e00-5d45-11e9-95da-51ab84dd63bc.png">

which we then plugged into the volume equation for the volume of water pumped per cycle:
<img width="172" alt="Screen Shot 2019-04-12 at 4 05 20 PM" src="https://user-images.githubusercontent.com/35718077/56066294-5f080b00-5d45-11e9-8839-fe3002af663e.png">
<img width="192" alt="Screen Shot 2019-04-12 at 4 05 24 PM" src="https://user-images.githubusercontent.com/35718077/56066302-63ccbf00-5d45-11e9-8a8e-41bfbbd738eb.png">
where h is the height of the drive pipe, and delta h is the difference in height between the height we want to pump water and the water level of the head tank (initial head in air chamber - water level in head tank = 600 m - 2.06 m)

**Comment by monroews** [comment]
The equations look great. How long is the calculated delta t compared with the measured delta t? Now you can calculate efficiency of pumping too!

**Comment by cheertsang** [comment]
**The theoretical time period in which water is being pumped into the air chamber is 0.0976 second**
**The theoretical amount of water pumped is: 48.73 milliliter**
We are skeptical because the time period and the amount of water pumped were a lot greater than the experimental values we got. In our experiments, the volume of water pumped per 1 cycle is 2.898 milliliter, which means that the ram pump is incredibly inefficient. 

```
v_f = 2.26*u.m/u.s #terminal velocity, experimentally determined
area = pc.area_circle(.02372*u.m) #area of drive pipe

#height of the drive pipe
h = 1.74*u.m

#height difference between height we want to pump water and water level of head tank
h1 = 2.06*u.m #height from bottom of drive pipe to top of water level in head tank
h2 = airchamber[0] #around 600 cm, make sure you run airchamber from first cell
delta_h = (h2 - h1).to(u.m)

delta_t = (v_f*h)/(c.GRAVITY*delta_h)
print('The theoretical time period in which water is being pumped into the air chamber is ' + str(delta_t))

volume = (0.5*area*v_f*delta_t).to(u.milliliter)

print('The theoretical amount of water pumped is: ' + str(volume))
```

**Comment by monroews** [comment]
Now the challenge is to learn why the ram pump is sooooo inefficient. I bet you remember that we are doing this because we suspected that the ram pump was inefficient! 

I suspect that the pressure trace is still not capturing the very rapid pressure pulse fully. The water in the drive pipe is stopping MUCH faster (by about a factor of 3 - check this!) then what theory predicts. Why is the water stopping so much faster? We don't have any doubts about F=ma! So either the water isn't traveling as fast as you thought OR the pressure at the bottom of the drive pipe is much greater than you thought. The pressure trace DOES exceed 600 cm of water. I bet the pressure actually goes MUCH higher than 600 cm of water and that we are missing that very high pulse because our pressure sensor is to far from the drive pipe. 

The very high pressure required to move the water into the the high pressure side of the system is due to the head loss through the small check valve. So time to experiment with a bigger check valve! Do you have the plumbing supplies you need to build and test this?
