### ISSUE TITLE
Measuring Force to Close Plate

### ISSUE THREAD

**Issue by alyssaju** [AguaClara/ram_pump#82]
Here are few ideas we brainstormed to measure the force to close the plate in the waste check valve:

1. We could use this compression force gauge directly on the plate to measure the force.
[compression force gauge](https://www.amazon.com/dp/B07HHNTB92/ref=sspa_dk_detail_1?psc=1&pd_rd_i=B07HHNTB92&pd_rd_w=x8SMo&pf_rd_p=8a8f3917-7900-4ce8-ad90-adf0d53c0985&pd_rd_wg=yXuXW&pf_rd_r=19H3DTJ2CPJJZ36ZFYDP&pd_rd_r=1d628b68-d7fc-4ad7-9ac1-c117fc9eca7d&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExTFlYTUFQQThESElOJmVuY3J5cHRlZElkPUEwMjQ3MzE3Mk9RMUpHRkJOVDEwRCZlbmNyeXB0ZWRBZElkPUEwMjMxMTY0VERJMDFNTU40UlpPJndpZGdldE5hbWU9c3BfZGV0YWlsJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==)

2. A centimeter of the rod extends past the cross-bar in the bottom check valve. We were thinking of threading this portion, attaching an eye nut, and hooking on a hanging scale to measure the force. 

@monroews

**Comment by monroews** [comment]
We need a device with much better resolution. We don't need the ability to measure 500 N. See if you can find one that can measure at least down to 0.1 N.

The product is reasonable for cost. The documentation is difficult to understand and full of typos. The product reads 0.0 until either +5N or -5N of force is applied. This deadband is very frustrating since at larger forces readings are provided to the nearest 0.1N. However, if you select the factory calibration in settings (override any zeroing of the sensor), my device settles on a 32.9N offset. From this bias I can measure smaller forces. I don't know why they insisted on not displaying any measurements between -5N and +5N.
